In [1]:
import ibm_db

In [2]:
import ibm_db_dbi

In [5]:
dsn = "DRIVER={{IBM DB2 ODBC DRIVER}};" + \
      "DATABASE=BLUDB;" + \
      "HOSTNAME=db2w-nnuudch.us-east.db2w.cloud.ibm.com;" + \
      "PORT=50001;" + \
      "PROTOCOL=TCPIP;" + \
      "UID=bluadmin;" + \
      "PWD=ZvOlyBQK71N3t@Zww0bhv_ILRLC1g;"

In [5]:
dsn2 = "DRIVER={{IBM DB2 ODBC DRIVER}};" + \
      "DATABASE=BLUDB;" + \
      "HOSTNAME=dashdb-txn-sbox-yp-dal09-04.services.dal.bluemix.net;" + \
      "PORT=50000;" + \
      "PROTOCOL=TCPIP;" + \
      "UID=rpm12613;" + \
      "PWD=p^xtzb19k9chqw0l;"

In [24]:
dsn3 =  "DATABASE=BLUDB;HOSTNAME=dashdb-txn-sbox-yp-dal09-04.services.dal.bluemix.net;PORT=50000;PROTOCOL=TCPIP;UID=rpm12613;PWD=p^xtzb19k9chqw0l;",

In [6]:
connect_ =  ibm_db.connect(dsn2, "", "")

In [25]:
connect2 = ibm_db.connect(dsn3, "", "")

Exception: Supplied Parameter is invalid

In [32]:
# test query
query = "SELECT * FROM RPM12613.INSURANCECLAIMS where income > 100;"
# run direct SQL
stmt = ibm_db.exec_immediate(connect_, query)
respo = ibm_db.fetch_both(stmt)

Exception: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "INCOME" is not valid in the context where it is used.  SQLSTATE=42703 SQLCODE=-206

In [31]:
query2 = "SELECT * FROM RPM12613.INSURANCECLAIMS WHERE INSURANCECLAIMS.Income > ?;"
param = 100

stm2 = ibm_db.prepare(connect_, query2)
ibm_db.bind_param(stm2, 1, param)

Exception: Describe Param Failed: [IBM][CLI Driver][DB2/LINUXX8664] SQL0206N  "INSURANCECLAIMS.INCOME" is not valid in the context where it is used.  SQLSTATE=42703 SQLCODE=-206

In [21]:
ibm_db.fetch_tuple(stmt)

('QZ44356',
 'Extended',
 'Bachelor',
 '10/31/16',
 'Unemployed',
 'F',
 94,
 '199471.14020',
 13,
 42,
 8,
 'Personal Auto',
 'Personal L3',
 'Offer 3',
 'Agent',
 'Four-Door Car',
 'Medium',
 '859.339127',
 '7/28/19',
 'Arizona',
 'Suburban')

In [20]:
import json
json.dumps(respo)

'{"Customer_ID": "BU79786", "0": "BU79786", "Coverage": "Basic", "1": "Basic", "Education": "Bachelor", "2": "Bachelor", "Claim_date": "5/28/16", "3": "5/28/16", "Employment_Status": "Employed", "4": "Employed", "Gender": "F", "5": "F", "Monthly_Premium_Auto": 69, "6": 69, "Income": "53990.96651", "7": "53990.96651", "Months_Since_Last_Claim": 32, "8": 32, "Months_Since_Policy_Inception": 5, "9": 5, "Number_of_Policies": 1, "10": 1, "Policy_Type": "Corporate Auto", "11": "Corporate Auto", "Policy_Level": "Corporate L3", "12": "Corporate L3", "Renew_Offer__Type": "Offer 1", "13": "Offer 1", "Sales_Channel": "Agent", "14": "Agent", "Vehicle_Class": "Two-Door Car", "15": "Two-Door Car", "Vehicle_Size": "Medium", "16": "Medium", "ClaimAmount": "887.688478", "17": "887.688478", "Processed_date": "2/22/19", "18": "2/22/19", "State": "Washington", "19": "Washington", "Location_Type": "Suburban", "20": "Suburban"}'

In [6]:
import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share the notebook.
client_214df47e76934414978e8de86462e5eb = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='fziFreL_tuVN0jjktBSAh1XokqP_I1VfO7imYPEGBkyR',
    ibm_auth_endpoint="https://iam.ng.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3-api.us-geo.objectstorage.service.networklayer.com')

body = client_214df47e76934414978e8de86462e5eb.get_object(Bucket='creditrisk-donotdelete-pr-dt5n5eiaxkqdkl',Key='credit_feedback_data.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df = pd.read_csv(body)
df.head()

,CheckingStatus,LoanDuration,CreditHistory,LoanPurpose,LoanAmount,ExistingSavings,EmploymentDuration,InstallmentPercent,Sex,OthersOnLoan,...,OwnsProperty,Age,InstallmentPlans,Housing,ExistingCreditsCount,Job,Dependents,Telephone,ForeignWorker,Risk
0,0_to_200,31,credits_paid_to_date,other,1889,100_to_500,less_1,3,female,none,...,savings_insurance,32,none,own,1,skilled,1,none,yes,No Risk
1,less_0,18,credits_paid_to_date,car_new,462,less_100,1_to_4,2,female,none,...,savings_insurance,37,stores,own,2,skilled,1,none,yes,No Risk
2,less_0,15,prior_payments_delayed,furniture,250,less_100,1_to_4,2,male,none,...,real_estate,28,none,own,2,skilled,1,yes,no,No Risk
3,0_to_200,28,credits_paid_to_date,retraining,3693,less_100,greater_7,3,male,none,...,savings_insurance,32,none,own,1,skilled,1,none,yes,No Risk
4,no_checking,28,prior_payments_delayed,education,6235,500_to_1000,greater_7,3,male,none,...,unknown,57,none,own,2,skilled,1,none,yes,Risk

In [2]:
import numpy as np
import scipy.stats as ss
def cramers_v(x, y):
    confusion_matrix = pd.crosstab(x,y)
    chi2 = ss.chi2_contingency(confusion_matrix)[0]
    n = confusion_matrix.sum().sum()
    phi2 = chi2/n
    r,k = confusion_matrix.shape
    phi2corr = max(0, phi2-((k-1)*(r-1))/(n-1))
    rcorr = r-((r-1)**2)/(n-1)
    kcorr = k-((k-1)**2)/(n-1)
    return np.sqrt(phi2corr/min((kcorr-1),(rcorr-1)))

In [3]:
catfeaturecorrs = {}
for k in df.dtypes.index:
    if df.dtypes[k] == 'object':
        print("correlation between" ,k, "and Credit Risk is: ", cramers_v(df[k], df.Risk))
        catfeaturecorrs.update({k: cramers_v(df[k], df.Risk)})

correlation between CheckingStatus and Credit Risk is:  0.4324260055152495
correlation between CreditHistory and Credit Risk is:  0.41971268807531414
correlation between LoanPurpose and Credit Risk is:  0.2984145233943896
correlation between ExistingSavings and Credit Risk is:  0.35999483766265195
correlation between EmploymentDuration and Credit Risk is:  0.46150549775645966
correlation between Sex and Credit Risk is:  0.061112114791633025
correlation between OthersOnLoan and Credit Risk is:  0.3292343098505328
correlation between OwnsProperty and Credit Risk is:  0.4488830327052889
correlation between InstallmentPlans and Credit Risk is:  0.17032149059809557
correlation between Housing and Credit Risk is:  0.3772845940470985
correlation between Job and Credit Risk is:  0.08839181408667872
correlation between Telephone and Credit Risk is:  0.3536995364387884
correlation between ForeignWorker and Credit Risk is:  0.0737206729224987
correlation between Risk and Credit Risk is:  0.9995503586857661

In [4]:
def filterTheDict(dictObj, callback):
    newDict = dict()
    # Iterate over all the items in dictionary
    for (key, value) in dictObj.items():
        # Check if item satisfies the given condition then add to new dict
        if callback((key, value)):
            newDict[key] = value
    return newDict

In [16]:
correlated_catfeats = dict(filter(lambda elem: elem[1] > 0.4, catfeaturecorrs.items()))
 
print('Filtered Dictionary : ')
correlated_catfeats

Filtered Dictionary :

{'CheckingStatus': 0.4324260055152495,
 'CreditHistory': 0.41971268807531414,
 'EmploymentDuration': 0.46150549775645966,
 'OwnsProperty': 0.4488830327052889,
 'Risk': 0.9995503586857661}

In [36]:
feature_vector = list(correlated_catfeats.keys())

#### feature_vector

In [20]:
{k: v for k, v in sorted(catfeaturecorrs.items(), key=lambda item: item[1])}

{'Sex': 0.061112114791633025,
 'ForeignWorker': 0.0737206729224987,
 'Job': 0.08839181408667872,
 'InstallmentPlans': 0.17032149059809557,
 'LoanPurpose': 0.2984145233943896,
 'OthersOnLoan': 0.3292343098505328,
 'Telephone': 0.3536995364387884,
 'ExistingSavings': 0.35999483766265195,
 'Housing': 0.3772845940470985,
 'CreditHistory': 0.41971268807531414,
 'CheckingStatus': 0.4324260055152495,
 'OwnsProperty': 0.4488830327052889,
 'EmploymentDuration': 0.46150549775645966,
 'Risk': 0.9995503586857661}

In [25]:
df['CreditRisk'] = df.Risk.astype("category").cat.codes

In [26]:
df.corr()['CreditRisk']

LoanDuration                0.442021
LoanAmount                  0.450247
InstallmentPercent          0.415928
CurrentResidenceDuration    0.425533
Age                         0.461028
ExistingCreditsCount        0.396117
Dependents                  0.229990
CreditRisk                  1.000000
Name: CreditRisk, dtype: float64

In [27]:
df.corr()['CreditRisk'].loc[abs(df.corr()['CreditRisk'])>0.4].sort_values(ascending=False)

CreditRisk                  1.000000
Age                         0.461028
LoanAmount                  0.450247
LoanDuration                0.442021
CurrentResidenceDuration    0.425533
InstallmentPercent          0.415928
Name: CreditRisk, dtype: float64

In [38]:
feature_vector.extend(list(df.corr()['CreditRisk'].loc[abs(df.corr()['CreditRisk'])>0.4].sort_values(ascending=False).index))

In [40]:
feature_vector

['CheckingStatus',
 'CreditHistory',
 'EmploymentDuration',
 'OwnsProperty',
 'Risk',
 'CreditRisk',
 'Age',
 'LoanAmount',
 'LoanDuration',
 'CurrentResidenceDuration',
 'InstallmentPercent']

In [54]:
df_filtered = df[feature_vector]

In [55]:
df_filtered.drop(['CreditRisk'], axis = 1, inplace= True)

In [56]:
df_filtered.shape

(5000, 10)

In [57]:
df_filtered.dtypes

CheckingStatus              object
CreditHistory               object
EmploymentDuration          object
OwnsProperty                object
Risk                        object
Age                          int64
LoanAmount                   int64
LoanDuration                 int64
CurrentResidenceDuration     int64
InstallmentPercent           int64
dtype: object

In [51]:
for j in df_filtered.dtypes.index:
    if df_filtered.dtypes[j] == 'object':
        print(j ,":")
        print(df_filtered[j].value_counts())
        print()

CheckingStatus :
no_checking    1993
less_0         1398
0_to_200       1304
greater_200     305
Name: CheckingStatus, dtype: int64

CreditHistory :
prior_payments_delayed    1686
credits_paid_to_date      1490
outstanding_credit         938
all_credits_paid_back      769
no_credits                 117
Name: CreditHistory, dtype: int64

EmploymentDuration :
1_to_4        1470
4_to_7        1400
greater_7      930
less_1         904
unemployed     296
Name: EmploymentDuration, dtype: int64

OwnsProperty :
savings_insurance    1660
car_other            1540
real_estate          1087
unknown               713
Name: OwnsProperty, dtype: int64

Risk :
No Risk    3330
Risk       1670
Name: Risk, dtype: int64

In [60]:
df_filtered.dtypes

CheckingStatus              object
CreditHistory               object
EmploymentDuration          object
OwnsProperty                object
Risk                        object
Age                          int64
LoanAmount                   int64
LoanDuration                 int64
CurrentResidenceDuration     int64
InstallmentPercent           int64
dtype: object

In [19]:
len(df.OwnsProperty.value_counts())

4

In [15]:
len(df)

21

In [35]:
cat_cols = []

In [42]:
pd.to_datetime(df.LoanDuration)

0      1970-01-01 00:00:00.000000031
1      1970-01-01 00:00:00.000000018
2      1970-01-01 00:00:00.000000015
3      1970-01-01 00:00:00.000000028
4      1970-01-01 00:00:00.000000028
5      1970-01-01 00:00:00.000000032
6      1970-01-01 00:00:00.000000009
7      1970-01-01 00:00:00.000000016
8      1970-01-01 00:00:00.000000011
9      1970-01-01 00:00:00.000000035
10     1970-01-01 00:00:00.000000005
11     1970-01-01 00:00:00.000000009
12     1970-01-01 00:00:00.000000027
13     1970-01-01 00:00:00.000000029
14     1970-01-01 00:00:00.000000004
15     1970-01-01 00:00:00.000000033
16     1970-01-01 00:00:00.000000004
17     1970-01-01 00:00:00.000000039
18     1970-01-01 00:00:00.000000004
19     1970-01-01 00:00:00.000000013
20     1970-01-01 00:00:00.000000015
21     1970-01-01 00:00:00.000000016
22     1970-01-01 00:00:00.000000034
23     1970-01-01 00:00:00.000000013
24     1970-01-01 00:00:00.000000015
25     1970-01-01 00:00:00.000000033
26     1970-01-01 00:00:00.000000023
27     1970-01-01 00:00:00.000000009
28     1970-01-01 00:00:00.000000010
29     1970-01-01 00:00:00.000000025
                    ...
4970   1970-01-01 00:00:00.000000016
4971   1970-01-01 00:00:00.000000025
4972   1970-01-01 00:00:00.000000032
4973   1970-01-01 00:00:00.000000014
4974   1970-01-01 00:00:00.000000036
4975   1970-01-01 00:00:00.000000020
4976   1970-01-01 00:00:00.000000019
4977   1970-01-01 00:00:00.000000010
4978   1970-01-01 00:00:00.000000008
4979   1970-01-01 00:00:00.000000032
4980   1970-01-01 00:00:00.000000032
4981   1970-01-01 00:00:00.000000033
4982   1970-01-01 00:00:00.000000009
4983   1970-01-01 00:00:00.000000032
4984   1970-01-01 00:00:00.000000018
4985   1970-01-01 00:00:00.000000053
4986   1970-01-01 00:00:00.000000004
4987   1970-01-01 00:00:00.000000022
4988   1970-01-01 00:00:00.000000032
4989   1970-01-01 00:00:00.000000025
4990   1970-01-01 00:00:00.000000036
4991   1970-01-01 00:00:00.000000011
4992   1970-01-01 00:00:00.000000008
4993   1970-01-01 00:00:00.000000015
4994   1970-01-01 00:00:00.000000012
4995   1970-01-01 00:00:00.000000027
4996   1970-01-01 00:00:00.000000011
4997   1970-01-01 00:00:00.000000032
4998   1970-01-01 00:00:00.000000038
4999   1970-01-01 00:00:00.000000012
Name: LoanDuration, Length: 5000, dtype: datetime64[ns]

In [38]:
def extract_categorical_vars(dfa, n_levels, target):
    for j in dfa.dtypes.index:    
        if dfa.dtypes[j] == 'object':
            if len(dfa[j].value_counts()) <= n_levels:
                cat_cols = df.dtypes.index()
            return cat_cols

In [12]:
    for j in dfa.index:    
        if dfa.dtypes[j] == 'object':
            if len(dfa[j].value_counts) <= n_levels:
                print(j)

NameError: name 'dfa' is not defined

In [39]:
extract_categorical_vars(df, 5, '')

['CheckingStatus']

In [24]:
cat_cols

NameError: name 'cat_cols' is not defined